// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_WEB_API_KEY']!,
        appId: '1:491367081694:web:bb5a47f0d8f0c4e04dc44f',
        messagingSenderId: '491367081694',
        projectId: 'ph-fare-calculator',
        authDomain: 'ph-fare-calculator.firebaseapp.com',
        storageBucket: 'ph-fare-calculator.firebasestorage.app',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY']!,
        appId: '1:491367081694:android:9fbd1b4d96e0b0cb4dc44f',
        messagingSenderId: '491367081694',
        projectId: 'ph-fare-calculator',
        storageBucket: 'ph-fare-calculator.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
        appId: '1:491367081694:ios:bb5a47f0d8f0c4e04dc44f',
        messagingSenderId: '491367081694',
        projectId: 'ph-fare-calculator',
        storageBucket: 'ph-fare-calculator.firebasestorage.app',
        iosBundleId: 'com.phFareCalculator',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_MACOS_API_KEY']!,
        appId: '1:491367081694:macos:bb5a47f0d8f0c4e04dc44f',
        messagingSenderId: '491367081694',
        projectId: 'ph-fare-calculator',
        storageBucket: 'ph-fare-calculator.firebasestorage.app',
        iosBundleId: 'com.phFareCalculator',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY']!,
        appId: '1:491367081694:windows:bb5a47f0d8f0c4e04dc44f',
        messagingSenderId: '491367081694',
        projectId: 'ph-fare-calculator',
        authDomain: 'ph-fare-calculator.firebaseapp.com',
        storageBucket: 'ph-fare-calculator.firebasestorage.app',
      );
}